# Generated by Django 3.1.3 on 2020-12-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('aplicationdoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('coursename', models.CharField(max_length=20)),
                ('studentname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('mono', models.CharField(max_length=100)),
                ('emall', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=1000)),
                ('distic', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('boardname', models.CharField(max_length=300)),
                ('tenmarks', models.CharField(max_length=100)),
                ('twmarks', models.CharField(max_length=100)),
                ('twboard', models.CharField(max_length=100)),
                ('graduation', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='myimage/image')),
                ('sign', models.ImageField(upload_to='myimage/sign')),
            ],
        ),
        migrations.CreateModel(
            name='Student_status',
            fields=[
                ('statusid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
