# Generated by Django 3.1.3 on 2020-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='myimage/image/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sign',
            field=models.ImageField(upload_to='myimage/sign/'),
        ),
    ]
